name: Build And Push to Dockerhub
on:
  push:
    branches:
      - 'v**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'
permissions:
  contents: read
jobs:
  main:
    name: Build Docker Image
    env:
      DOCKER_BUILD_ENABLED: ${{ secrets.DOCKER_BUILD_ENABLED }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Branch Name
        id: ci_branch_name
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        shell: bash
        run: echo "branch=$(echo ${{github.ref_name}})" >> $GITHUB_OUTPUT

      - name: Get current date
        id: date
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        shell: bash
        run: echo "::set-output name=date::$(date +'%Y-%m-%d%H:%M:%S')" >> $GITHUB_OUTPUT

      -name: Create tag
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: ${{ steps.date.outputs.date }}
          BRANCH_NAME: ${{ steps.ci_branch_name.outputs.branch }}

      - name: Build and Push branch
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            "bigbluebutton/bbb-build:${{ env.BRANCH_NAME }}-${{ env.TAG_NAME }}"
          context: .
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
